"""Pydantic models describing the ``spec`` of each custom resource.

These models are the single source of truth for both:

* runtime parsing/validation in the resource handlers (``resources/*.py``), and
* the CustomResourceDefinition ``openAPIV3Schema`` generated by
  ``scripts/gen_crds.py`` into ``chart/airflow-k8s-operator-crds``.

Add or change a field here, run ``make generate``, and commit the regenerated
CRDs -- CI (generate-check) fails if they drift.
"""

from typing import ClassVar

from pydantic import BaseModel, ConfigDict, Field

GROUP = "airflow.drfaust92"
API_VERSION = "v1beta1"

_TEAM_NAME_DESC = (
    "Team for Airflow 3 multi-team mode. Requires multi-team mode enabled and "
    "the team to exist in Airflow, otherwise the API may reject the resource. "
    "Ignored on Airflow 2."
)


class SecretRef(BaseModel):
    """Reference to a key within a Kubernetes Secret."""

    model_config = ConfigDict(populate_by_name=True)

    name: str = Field(description="The name of the Kubernetes Secret.")
    key: str = Field(description="The key within the Secret.")


class SecretValue(BaseModel):
    """A value provided directly or sourced from a Kubernetes Secret."""

    model_config = ConfigDict(populate_by_name=True)

    value: str | None = Field(default=None, description="The direct value.")
    secretRef: SecretRef | None = Field(
        default=None, description="Reference to a Kubernetes Secret."
    )


class ConnectionSpec(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    crd: ClassVar[dict] = {
        "kind": "Connection",
        "plural": "connections",
        "singular": "connection",
        "short_names": ["conns", "conn"],
    }

    conn_type: str | None = Field(
        default=None, alias="connType", description="The connection type."
    )
    description: str | None = Field(
        default=None, description="The connection description."
    )
    host: str | None = Field(default=None, description="The connection host.")
    login: SecretValue | None = Field(
        default=None, description="The connection login (value or secretRef)."
    )
    password: SecretValue | None = Field(
        default=None, description="The connection password (value or secretRef)."
    )
    port: int | None = Field(
        default=None,
        description="The connection port.",
        json_schema_extra={"format": "int32"},
    )
    schema_: str | None = Field(
        default=None, alias="schema", description="The connection schema."
    )
    extra: str | None = Field(default=None, description="The connection extra field.")
    team_name: str | None = Field(
        default=None, alias="teamName", description=_TEAM_NAME_DESC
    )


class VariableSpec(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    crd: ClassVar[dict] = {
        "kind": "Variable",
        "plural": "variables",
        "singular": "variable",
        "short_names": ["vars", "var"],
        # Exactly one of value / secretRef must be set.
        "spec_one_of": [{"required": ["value"]}, {"required": ["secretRef"]}],
    }

    value: str | None = Field(
        default=None, description="The variable value (direct value)."
    )
    secretRef: SecretRef | None = Field(
        default=None,
        description="Reference to a Kubernetes Secret for the variable value.",
    )
    description: str | None = Field(
        default=None, description="The variable description."
    )
    team_name: str | None = Field(
        default=None, alias="teamName", description=_TEAM_NAME_DESC
    )


class PoolSpec(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    crd: ClassVar[dict] = {
        "kind": "Pool",
        "plural": "pools",
        "singular": "pool",
        "short_names": ["pls", "pl"],
    }

    slots: int = Field(
        description=(
            "The maximum number of slots that can be assigned to tasks. One job "
            "may occupy one or more slots."
        )
    )
    include_deferred: bool = Field(
        default=False,
        alias="includeDeferred",
        description="Whether to include deferred tasks in the pool.",
    )
    description: str | None = Field(default=None, description="The pool description.")
    team_name: str | None = Field(
        default=None, alias="teamName", description=_TEAM_NAME_DESC
    )


# Order here drives the order the CRD files are generated in.
SPECS = [ConnectionSpec, PoolSpec, VariableSpec]
