#!/usr/bin/env python
"""Generate the CustomResourceDefinition manifests from the Pydantic spec models.

Single source of truth: ``resources/schemas.py``. Run ``make generate`` (or
``python scripts/gen_crds.py``) after changing a spec model, and commit the
result. CI (generate-check) fails if the committed CRDs are stale.
"""

import pathlib
import sys

import yaml

# Allow running as `python scripts/gen_crds.py` from the repo root.
_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from resources.schemas import API_VERSION, GROUP, SPECS  # noqa: E402

CRD_DIR = _ROOT / "chart" / "airflow-k8s-operator-crds" / "templates"

HEADER = (
    "# Generated by scripts/gen_crds.py from resources/schemas.py -- DO NOT EDIT.\n"
    "# Run `make generate` after changing a spec model.\n"
)

_PRINTER_COLUMNS = [
    {"name": "Phase", "type": "string", "jsonPath": ".status.phase"},
    {"name": "Message", "type": "string", "jsonPath": ".status.message"},
]

_STATUS_SCHEMA = {
    "type": "object",
    "x-kubernetes-preserve-unknown-fields": True,
    "properties": {
        "phase": {
            "type": "string",
            "description": "Last reconciliation outcome (Synced or Error).",
        },
        "message": {
            "type": "string",
            "description": "Human-readable detail about the last reconciliation.",
        },
    },
}

# JSON Schema keys that have no place in a CRD openAPIV3Schema.
_DROP = {"title", "default", "additionalProperties", "$defs"}


def _to_crd_schema(node, defs):
    """Convert a pydantic JSON-schema node into a CRD openAPIV3Schema node.

    Inlines ``$ref`` against ``defs``, collapses ``X | None`` unions down to the
    non-null branch (all CRD fields are optional-by-absence), and drops keys
    Kubernetes rejects.
    """
    if isinstance(node, list):
        return [_to_crd_schema(n, defs) for n in node]
    if not isinstance(node, dict):
        return node

    if "$ref" in node:
        ref = node["$ref"].split("/")[-1]
        base = _to_crd_schema(defs[ref], defs)
        for key, value in node.items():
            if key != "$ref" and key not in _DROP:
                base[key] = _to_crd_schema(value, defs)
        return base

    for combiner in ("anyOf", "oneOf"):
        if combiner in node:
            branches = [
                b
                for b in node[combiner]
                if not (isinstance(b, dict) and b.get("type") == "null")
            ]
            base = _to_crd_schema(branches[0], defs)
            for key, value in node.items():
                if key != combiner and key not in _DROP:
                    base[key] = _to_crd_schema(value, defs)
            return base

    return {
        key: _to_crd_schema(value, defs)
        for key, value in node.items()
        if key not in _DROP
    }


def _spec_schema(model):
    js = model.model_json_schema(by_alias=True)
    defs = js.get("$defs", {})
    schema = _to_crd_schema(js, defs)
    one_of = model.crd.get("spec_one_of")
    if one_of:
        schema["oneOf"] = one_of
    return schema


def _crd(model):
    meta = model.crd
    return {
        "apiVersion": "apiextensions.k8s.io/v1",
        "kind": "CustomResourceDefinition",
        "metadata": {
            "name": f"{meta['plural']}.{GROUP}",
            "annotations": {"helm.sh/resource-policy": "keep"},
        },
        "spec": {
            "group": GROUP,
            "scope": "Namespaced",
            "names": {
                "kind": meta["kind"],
                "plural": meta["plural"],
                "singular": meta["singular"],
                "shortNames": meta["short_names"],
            },
            "versions": [
                {
                    "name": API_VERSION,
                    "served": True,
                    "storage": True,
                    "subresources": {"status": {}},
                    "additionalPrinterColumns": _PRINTER_COLUMNS,
                    "schema": {
                        "openAPIV3Schema": {
                            "type": "object",
                            "properties": {
                                "spec": _spec_schema(model),
                                "status": _STATUS_SCHEMA,
                            },
                        }
                    },
                }
            ],
        },
    }


def main():
    CRD_DIR.mkdir(parents=True, exist_ok=True)
    for model in SPECS:
        crd = _crd(model)
        body = yaml.dump(crd, sort_keys=False, default_flow_style=False, width=4096)
        out = CRD_DIR / f"{model.crd['singular']}.yaml"
        out.write_text(HEADER + body)
        print(f"wrote {out.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
